# -*- generated by 1.0.9 -*-
import da
PatternExpr_181 = da.pat.TuplePattern([da.pat.ConstantPattern('Ping')])
PatternExpr_186 = da.pat.FreePattern('p')
PatternExpr_205 = da.pat.TuplePattern([da.pat.ConstantPattern('Ping')])
PatternExpr_210 = da.pat.FreePattern('p')
PatternExpr_253 = da.pat.TuplePattern([da.pat.ConstantPattern('Pong')])
PatternExpr_258 = da.pat.FreePattern('rclk')
PatternExpr_278 = da.pat.TuplePattern([da.pat.ConstantPattern('Pong')])
_config_object = {}
import sys

class Pong(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PongReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PongReceivedEvent_0', PatternExpr_181, sources=[PatternExpr_186], destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PongReceivedEvent_1', PatternExpr_205, sources=[PatternExpr_210], destinations=None, timestamps=None, record_history=None, handlers=[self._Pong_handler_204])])

    def setup(self, total_pings, **rest_328):
        super().setup(total_pings=total_pings, **rest_328)
        self._state.total_pings = total_pings
        self.output(self._state.total_pings)
        self.output('total_pings')

    def run(self):
        a = False
        super()._label('_st_label_176', block=False)
        _st_label_176 = 0
        while (_st_label_176 == 0):
            _st_label_176 += 1
            if (len([p for (_, (_, _, p), (_ConstantPattern197_,)) in self._PongReceivedEvent_0 if (_ConstantPattern197_ == 'Ping')]) == self._state.total_pings):
                _st_label_176 += 1
            else:
                super()._label('_st_label_176', block=True)
                _st_label_176 -= 1

    def _Pong_handler_204(self, p):
        self.output('Pinged')
        self.send(('Pong',), to=p)
    _Pong_handler_204._labels = None
    _Pong_handler_204._notlabels = None

class Ping(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PingReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PingReceivedEvent_0', PatternExpr_253, sources=None, destinations=None, timestamps=[PatternExpr_258], record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PingReceivedEvent_1', PatternExpr_278, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Ping_handler_277])])

    def setup(self, p, nrounds, **rest_328):
        super().setup(p=p, nrounds=nrounds, **rest_328)
        self._state.p = p
        self._state.nrounds = nrounds
        pass

    def run(self):
        for i in range(self._state.nrounds):
            clk = self.logical_clock()
            self.send(('Ping',), to=self._state.p)
            super()._label('_st_label_250', block=False)
            rclk = None

            def ExistentialOpExpr_251():
                nonlocal rclk
                for (_, (rclk, _, _), (_ConstantPattern269_,)) in self._PingReceivedEvent_0:
                    if (_ConstantPattern269_ == 'Pong'):
                        if (rclk > clk):
                            return True
                return False
            _st_label_250 = 0
            while (_st_label_250 == 0):
                _st_label_250 += 1
                if ExistentialOpExpr_251():
                    _st_label_250 += 1
                else:
                    super()._label('_st_label_250', block=True)
                    _st_label_250 -= 1
            else:
                if (_st_label_250 != 2):
                    continue
            if (_st_label_250 != 2):
                break

    def _Ping_handler_277(self):
        self.output('Ponged')
    _Ping_handler_277._labels = None
    _Ping_handler_277._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
    _config_object = {'clock': 'Lamport'}

    def run(self):
        nrounds = 3
        npings = 3
        pong = self.new(Pong, [(nrounds * npings)], num=1)
        ping = self.new(Ping, num=(npings + 1))
        self._setup(ping, (pong, nrounds))
        self._start(pong)
        self._start(ping)
